apiVersion: v1
kind: Service
metadata:
    name: "jobbiecluster-1db6"
    labels:
        app: "jobbiecluster-1db6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jobbiecluster-1db6"