on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jobbieregistry.azurecr.io
        username: ${{ secrets.acr_jobbieregistry_username }}
        password: ${{ secrets.acr_jobbieregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Microservices.WebApi/Client.Microservice" -f  "Microservices.WebApi/Client.Microservice/Dockerfile" -t jobbieregistry.azurecr.io/jobbiecluster:${{ github.sha }} --label dockerfile-path=Microservices.WebApi/Client.Microservice/Dockerfile
        docker push jobbieregistry.azurecr.io/jobbiecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jobbiecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jobbie-cluster87c2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jobbie-cluster87c2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jobbie-cluster87c2
        container-registry-url: jobbieregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_jobbieregistry_username }}
        container-registry-password: ${{ secrets.acr_jobbieregistry_password }}
        secret-name: jobbieclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jobbie-cluster87c2
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          jobbieregistry.azurecr.io/jobbiecluster:${{ github.sha }}
        imagepullsecrets: |
          jobbieclustedockerauth
